version: "3.9"

services:
  biodrop:
    container_name: biodrop
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: biodrop-app
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
